### ISSUE TITLE
FAQ - Testando components

### ISSUE THREAD

**Issue by oieduardorabelo** [daviferreira/react-sanfona#1]
@daviferreira :tada: 

achei massa você testar o component em si, e não só a integração (Stores/Actions etc), 

https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItemTest.jsx#L16-l51

vi muita gente dizendo que testar o componente em sí, não é muito viável (até relacionaram com teste end-2-end),

cheguei a trocar uma idéia com o Dan Abramov e até vi alguns argumentos do Ryan Florence, dizendo que, realmente, eles preferem testar outras partes ao invés do componente em si,

e, tirando uma conclusão de suíte de testes para app's em React:

- **Jest**, ninguém recomenda
- **Karma**, ótimo se você não puder evitar testes no DOM
- **Mocha**, ótimo se você puder evitar testes no DOM

Estou caçando argumentos e exemplos para isso e tentar achar um mmc,

Atualmente, também uso Mocha, e testo apenas a integração e não o componente,

Queria sua opinião sobre :+1:

**Comment by daviferreira** [comment]
Fala Eduardo,

cara, na verdade um dos objetivos desse projetinho era justamente testar mocha com jsdom porque eu to cansado de karma+phantom (demora 30 secs pra dar start nos testes em um projeto grande...). 

Minha opinião é bem parecida com a sua. Já tentei usar JEST e a documentação é muito ruim e tinha coisas básicas na época como não dar suporte a NODE_PATH etc. Atualmente uso sempre karma + phantom, mas o phantom é lento demais... Acho que o segredo é usar um dom virtual, mas acredito que vou ter vários problemas/restrições, pelo que li a API dele tem várias inconsitências.

Enfim, no quesito velocidade mocha+jsdom acho que é imbatível, mas ainda preciso de mais dados pra saber se é o setup ideal :)

Sobre testar componentes ou não... Eu gosto de testar se o componente for bem pequeno e testar mais as lógicas de Interface. Tipo um comportamento de toggle etc. Acho que não custa nada testar isso.

Valeu!
