### ISSUE TITLE
How to prevent default onClick over AccordionItem

### ISSUE THREAD

**Issue by yascov** [daviferreira/react-sanfona#101]
Hello,

Thank very much for your work. 
is it possible to prevent onClick over AccordionItem title so users can click on buttons inside it?
This means I will control the expanded state. 

Thank you

![screen shot 2016-11-23 at 3 13 09 pm](https://cloud.githubusercontent.com/assets/10214494/20567177/b7997ee8-b18f-11e6-9eb4-9305103d1b62.png)

**Comment by psimyn** [comment]
One way currently is to pass a custom component as `title` prop, then add an onClick handler for buttons 

```
function toggleButton(evt) {
  evt.stopPropagation() // prevent the onClick from reaching AccordionItem title
}

...

<AccordionItem
  title={<h2>Some Text  <button onClick={toggleButton}>A button</button></h2>}
/>
```

I don't think you can currently prevent the outer `onClick` without capturing the event - that would be useful for managing the state outside of the component

**Comment by yascov** [comment]
Ok thank you. Got it.
