### ISSUE TITLE
When the page with my accordion loads it defaults to open the first one 

### ISSUE THREAD

**Issue by smanwaring** [daviferreira/react-sanfona#102]
When my accordion item loads it defaults to expanding the first item on the list. How can I prevent this (so that on load none of the accordion items are open)?

Thank you! I love this library otherwise :)

     <Accordion allowMultiple={false} onChange={this.onClickProject}>
                {projectLoop && projectLoop.map((instance, index) => {
                  const titleBar = (
                      <div className="project-title" onClick={this.onClickProject}>
                        <span>{instance.name}</span>

                        <Link>
                          <span className="icon-height"style={{float: 'right'}} onClick={(evt) => {
                            this.props.fetchCollabs(instance);
                            hashHistory.push('/collabs');
                            evt.stopPropagation() // **LEAVE THIS HERE!** it makes sure we don't trigger AccordionItemTitle onClick of the icon
                          }}>
                          <i className="small material-icons">supervisor_account</i>
                          </span>
                        </Link>

                      </div>
                    )
                    return (
                        <AccordionItem title={titleBar} key={index} slug={index} className="card-panel left-justified-text">
                                {instance.commits && instance.commits.map((commit, index) => {
                                  return (
                                    <div className="item-commit-border" key={commit.id}
                                      onClick={() => {this.onClickCommit(index)}}>
                                      <div className="commit-message commit-color">{commit.message.slice(0, 20)}</div>
                                      <div className="item-commit-details"><span className="commit-message commit-info-font commit-date">{`On ${Moment(commit.date).format('MMMM Do')}`}</span><span className="commit-info-font">{`by ${commit.committer}`}</span></div>
                                    </div>
                                    )
                                })}
                        </AccordionItem>
                        );
                    })}
            </Accordion>

**Comment by chehitskenniexd** [comment]
So taking a look at the demo code, activeItems is set when creating the Accordian.
So if you do:
>  <Accordion allowMultiple={false} onChange={this.onClickProject} activeItem={-1}>
This will cause the Accordian to register none of the valid activeItems and it closes all of them by default!

**Comment by smanwaring** [comment]
changing the activeItem={-1} on the Accordion solved the issue.

**Comment by choosenvictim** [comment]
Hi, I am also facing the same issue. I have set ```activeItem={-1}``` ,but still accordion renders with first AccordionItem opened by default.
Here is my code:
```
<Accordion allowMultiple={false} activeItem={-1}>
  {props.topics.map((topic, i) => {
    return (
      <AccordionItem key={i} className={style.accordionItem} title={topic.name}>
        {renderTopicsList(topic.children)}
      </AccordionItem>
    );
  })}
</Accordion>
```

**Comment by choosenvictim** [comment]
Duhhhh !!!!
It should be ```activeItems```, and not ```activeItem```, since its a list and grammatically its plural. That solves my problem.
Its written properly in docs, but not here :)
