### ISSUE TITLE
With new version onClose event is triggering by itself

### ISSUE THREAD

**Issue by sreevarsh** [daviferreira/react-sanfona#108]
Hi, I upgraded to latest version of react-sanfona(0.1.0) and my onClose and onExpand events are not working as expected, when I try to open an AccordionItem it closes by itself. below is the code snippet.
`<AccordionItem
id={"test"+c}
uuid={"test"+c}
onClose={() => this.hideItem(value)}
onExpand={() => this.showItem(value)}
title={value}
slug={c} key={id}
allowMultiple={true}
expanded={true}>`

Thank you

**Comment by psimyn** [comment]
what are your hideItem/showItem functions doing? If I remember right the onExpand/onClose functions get called after clicking (so the items are already expanding).

Thanks for raising

**Comment by choosenvictim** [comment]
I am also having the same issue. It works fine if I don't provide onClose and onExpand options to AccordionItem, but when I provide them, AccordionItem doesn't open at all.
Then I put debug points in onClose and onExpand callbacks and noticed that ```onClose``` is getting fired right after ```onExpand```
