### ISSUE TITLE
AccordionItem breaks non latin characters inside

### ISSUE THREAD

**Issue by luckyraul** [daviferreira/react-sanfona#109]
```200,00 руб.``` transforms to ```200,00 &#8399;```

**Comment by psimyn** [comment]
Do you have a complete example of this? Is `200,00 руб` set in the title or the body?

I tried in both of those and it displayed ok.

Thanks for raising

**Comment by luckyraul** [comment]
I am sorry. 
This was different back-end response for mobile view, where I use your component. 
&#8399; equals ₽ in html
