### ISSUE TITLE
Trouble defaulting to closed Accordion with form components in AccordionItem

### ISSUE THREAD

**Issue by bwbarron** [daviferreira/react-sanfona#111]
Right now I just have a single `AccordionItem`:
```js
<Accordion style={STYLES.search} activeItems={-1}>
    <AccordionItem title='Search Form'>
        <SearchForm />
    </AccordionItem>
</Accordion>
```
I added the `activeItems={-1}` and it renders closed as expected. The problem is, when I expand it and click on a form component (right now there is only a single text field), it closes immediately. If I remove the `activeItems={-1}`, it renders opened, but I am able to click on the text field without the `AccordionItem` closing.

I am using version 0.1.0.

**Comment by project707** [comment]
I am having the same problem on 0.2.3 where any activity in a form element in the content closes it, but I have not set activeItems at all (nor do i fully understand what that prop is for). Any idea how to stop this from happening?

**Comment by daviferreira** [comment]
Dupe #124
