### ISSUE TITLE
Overflow breaks my app

### ISSUE THREAD

**Issue by luckyraul** [daviferreira/react-sanfona#112]
https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItem/index.jsx#L76

introduced in https://github.com/daviferreira/react-sanfona/pull/97

I can't move up anything from body to item header position.

It should be visible on expanded and hidden on opposite

**Comment by amitzur** [comment]
I'm not sure this is correct. With this change (PR #113) the content shows up broken during expand. Why should overflow be visible when expanding?

**Comment by amitzur** [comment]
btw, the gh-pages branch still doesn't have this change and therefore works beautifully. When running the source code from master (or the npm package) it suddenly breaks.

**Comment by morgs32** [comment]
Yea revert that!

**Comment by daviferreira** [comment]
Sorry, should be fixed on 0.4.2

**Comment by luckyraul** [comment]
@daviferreira may be you should update demo?
