### ISSUE TITLE
Pass to title props a function

### ISSUE THREAD

**Issue by yuripramos** [daviferreira/react-sanfona#114]
Is there any way or idea in how to implement a function inside the <AccordionItem /> ?

Im thinking in some stuff like that: 
> 
>       <AccordionItem title={this.renderMateriaSqueezed.bind(this)} key={key}>
>         <HeaderComponent title={item.title} id={item.id} subtitle={item.subtitle} category={item.categoria} />
>         <Content content={item.content[0]} />
>         <Footer />
>       </AccordionItem>

I need to render a whole content as "title" or some way to load previous content before the accordion is clicked. I'm able to help you guys in this feature if there's no way to do this yet.

**Comment by SuttJ** [comment]
I don't believe there's a way to implement a function inside of title. However, if the reason you're using the function is to render a component, you can simply write the component directly in the title tag. Like this:
```
<AccordionItem className={item.title} key={key} title={ <div className="theTitle">
                                                               {item.title}
                                                              <div className="innerTitle">
                                                               {item.title.info}
                                                              </div>
                                                         </div>
                                                       } 
                                          
</AccordionItem>
                                         
```

**Comment by yuripramos** [comment]
I was trying to use [getter functions ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/get) but without success, your solution are working for me, but idk why. The documentation says that this prop only accepts string and object.
