### ISSUE TITLE
AccordionItem closes after button click

### ISSUE THREAD

**Issue by horak** [daviferreira/react-sanfona#117]
I have something like this. 

```javascript
  handleDeleteUser = (e) => {
    if (this.state.confirm) {
      this.setState({
        confirm: false 
      })
    } else {
      this.setState({
        confirm: true 
      })
    }
  }

...

<button type='button' id={id} onClick={this.handleDeleteUser}>
  {this.state.confirm ? 'Really?' : 'Delete'}
</button>
```

Setting state within the handler closes all open accordions. Any ideas why?

**Comment by psimyn** [comment]
Is the button within an AccordionTitle or inside of an item? do you have a more complete example?

**Comment by horak** [comment]
Yup, that's the one, sorry about that.

**Comment by project707** [comment]
This kind of seems different to me in that this is closing accordions and in #116 it seems like the accordion functionality breaks, but maybe I'm misreading that?
