### ISSUE TITLE
Click on form outside/into Accordion

### ISSUE THREAD

**Issue by s-mikulich** [daviferreira/react-sanfona#124]
Hi, I have a problem. Accordion Item is opening If I click on input outside or inside of the Accordion. 
Thanks.

**Comment by kkashou** [comment]
+1

**Comment by kkashou** [comment]
It seems to be looking at the onChange event ... just not sure how to bypass the onchange so that it doesn't listen to it.

**Comment by daviferreira** [comment]
Can't really reproduce this, could you provide some example code?

**Comment by kkashou** [comment]
I created an example to see what happens when you click on https://codesandbox.io/s/yp0kl7305j

Hopefully this helps with the issue I am dealing with.

**Comment by daviferreira** [comment]
Just published 0.4.0 with a fix, can you test it please?

**Comment by daviferreira** [comment]
https://github.com/daviferreira/react-sanfona/commit/cad25973545a9ce8b57f198ef1ee502fd007d52a

**Comment by kkashou** [comment]
Thank you!

**Comment by LukeVibes** [comment]
Has this issue been fixed? I have been dealing with issue all day and praying for a solution
