### ISSUE TITLE
overflow always hidden when AccordeonItem has images

### ISSUE THREAD

**Issue by Delapouite** [daviferreira/react-sanfona#125]
Hello

https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItem/index.js#L89

I have an AccordeonItem with images inside, tooltips, and `<react-select>` components.
It used to work in version `0.0.15`. I've just updated to `0.0.4`. Because of the line above, the tooltips and the `<react-select>` are always truncated because of the overflow.

Is there any reason for forcing this value to `hidden` instead of using a check like on:
https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItem/index.js#L76

?

**Comment by daviferreira** [comment]
Should be fixed on 0.4.2
