### ISSUE TITLE
Null AccordionItem

### ISSUE THREAD

**Issue by luckyraul** [daviferreira/react-sanfona#128]
Same bug as I fixed long time ago. https://github.com/daviferreira/react-sanfona/issues/107
1.0

Element of Accordion children array can be null and should be ignored.

https://github.com/daviferreira/react-sanfona/pull/129

**Comment by daviferreira** [comment]
https://github.com/daviferreira/react-sanfona/commit/6d8f34ebab699c73f0ce9abe4b77d99b314b195e
