### ISSUE TITLE
Multiple accordions on one page screws up Accordion collapse duration

### ISSUE THREAD

**Issue by maasha** [daviferreira/react-sanfona#140]
I have multiple accordions on a page. Collapsing accordions sometimes skip the duration and happens instantly. Ideas?

**Comment by abhn** [comment]
This used to happen (in my case) when the data inside the accordion was being fetched from an API. The lag made the accordion to skip the animation.

**Comment by daviferreira** [comment]
@maasha would be great if you could provide an example, but I guess we need some kind of `async` prop/flag to control that.
