### ISSUE TITLE
Can i Add HTML into title?

### ISSUE THREAD

**Issue by BeatDeer** [daviferreira/react-sanfona#160]
I want to add my custom html icon
`<AccordionItem
              title={'Detalles de la Obra <div class="assets_pci pci_accordion_toggle"></div>'}
              className="accordeonDetails wrapper"
              style={styles.accordeonDetails}
            >`

But print the string.

**Comment by abhn** [comment]
Create a new component with that HTML,

> const CustomElement = <div>Detalles de la Obra <div class="assets_pci pci_accordion_toggle"></div></div>
> <AccordionItem title={CustomElement} className="accordeonDetails wrapper" style={styles.accordeonDetails} >

And you should be good.

**Comment by BeatDeer** [comment]
Thanks @abhn  I will try and tell you what happens... 🤞
