### ISSUE TITLE
max-height not getting removed after animation

### ISSUE THREAD

**Issue by abhn** [daviferreira/react-sanfona#173]
I tried looking for a fix to this issue and found that it has already been fixed in https://github.com/daviferreira/react-sanfona/pull/56

However, I'm still facing this issue where the content overflows and max-height to the body of react-safona prevents it from expanding to the required height. 

Attaching the screenshot.

![image](https://user-images.githubusercontent.com/6270406/36482678-162d98de-173a-11e8-9311-9f6de647b465.png)

**Comment by daviferreira** [comment]
Hmm, can't really reproduce it. Could you provide a fiddle or something?

**Comment by abhn** [comment]
@daviferreira sorry, couldn't get back on this, and providing a fiddle was a little tricky as there was a lot of dynamic data flowing (plus even I couldn't reproduce it except for the first time after loading the page).

So the problem was that the content in the accordion body had some margin top and bottom, that wasn't getting picked up for the calculation of max-height, leading to things getting clipped. I changed the margins to paddings and voila! 

Thanks!
