### ISSUE TITLE
onHover property

### ISSUE THREAD

**Issue by alex6633** [daviferreira/react-sanfona#189]
Hi @daviferreira ,
Thank you so much for this wonderful library. 
Is there something that I can do to achieve this requirement ?
Like "onExpand" and "onCollapse" props Can I also use "onHover" prop where in I can automatically expand or collapse my accordion onHover of it.. ?

**Comment by leonascimento** [comment]
@daviferreira Can I work on this feature?

**Comment by daviferreira** [comment]
@leonascimento claro! 💪
