### ISSUE TITLE
overflow is always 'hidden' when accordion item has images

### ISSUE THREAD

**Issue by alexeychikk** [daviferreira/react-sanfona#193]
Please, check these lines
https://github.com/daviferreira/react-sanfona/blob/417f141208c1c854c341ec8cc4c5891a9ad035ba/src/AccordionItem/index.js#L112-L115
I think this line 
https://github.com/daviferreira/react-sanfona/blob/417f141208c1c854c341ec8cc4c5891a9ad035ba/src/AccordionItem/index.js#L114
must be replaced with
`overflow: expanded ? 'visible' : 'hidden'`
Or probably the problem is that componentDidUpdate does not react to setState properly after images are preloaded.
Quick fix will be greatly appreciated!

**Comment by alexeychikk** [comment]
Anyone who is experiencing the same issue, as workaround you can replace img with div or something with inline background style.

**Comment by daviferreira** [comment]
@alexeychikk that's exactly the problem and you gave the solution already, don't you want to submit a PR? :)
