### ISSUE TITLE
Render Open Accordion

### ISSUE THREAD

**Issue by monkecheese** [daviferreira/react-sanfona#33]
Is there a way (using props or something else) to set the Accordion so that all Accordion Items are showing open on page load?  I see that there is a way to select a certain Item to render open on page load using the prop "selectedIndex", but that's not quite what I'm looking for.  I need them to be all "open" when the page loads.  Thanks in advance!

**Comment by daviferreira** [comment]
@monkecheese can you try with the latest version? I have removed `selectedIndex` prop. Now you should just use `activeItems` and pass an array.

```
<Accordion allowMultiple={true} activeItems={[0, 1, 2, 3, 4]}>
  {[1, 2, 3, 4, 5].map((item) => {
    return (
      <AccordionItem title={`Item ${ item }`} key={item}>
        <div>
          {`Item ${ item } content`}
          {item === 3 ? <p><img src="http://i.giphy.com/nIMpbXH2WfYRi.gif" /></p> : null}
        </div>
      </AccordionItem>
    );
  })}
</Accordion>
```

**Comment by monkecheese** [comment]
Very nice!  Works beautifully.
