### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by mpbill** [daviferreira/react-sanfona#4]
when webpack tries to run on any files where i have required('react-sanfona') i get the following errors:
ERROR in /home/mpbill/NodeTest/~/react-sanfona/dist-modules/AccordionItem/index.js
Module not found: Error: Cannot resolve module 'classnames' in /home/mpbill/NodeTest/node_modules/react-sanfona/dist-modules/AccordionItem
 @ /home/mpbill/NodeTest/~/react-sanfona/dist-modules/AccordionItem/index.js 31:18-39

ERROR in /home/mpbill/NodeTest/~/react-sanfona/dist-modules/AccordionItem/index.js
Module not found: Error: Cannot resolve module 'uuid' in /home/mpbill/NodeTest/node_modules/react-sanfona/dist-modules/AccordionItem
 @ /home/mpbill/NodeTest/~/react-sanfona/dist-modules/AccordionItem/index.js 39:12-27

any ideas?

**Comment by daviferreira** [comment]
Should be fine now with 0.0.3, added `classnames` as dependency. Let me know if you still get it!

**Comment by bogdan-soare** [comment]
Hi @daviferreira ,

I also get the error `Module not found: Error: Cannot resolve module 'uuid' in /Users/bogdan.soare/Sites/mylocalmcds/hq-admin/node_modules/react-sanfona/dist-modules/AccordionItem
 @ ./~/react-sanfona/dist-modules/AccordionItem/index.js 21:12-27` . I have version 0.0.3.
I think you should add `uuid` as a dependency also.
Thanks.

**Comment by daviferreira** [comment]
Done :)

**Comment by daviferreira** [comment]
https://github.com/daviferreira/react-sanfona/commit/8710714001b42c50ddd5c6fa8519b0bc20e9c950

Thanks! :)

**Comment by bogdan-soare** [comment]
Awesome, thanks :)
