### ISSUE TITLE
How create an Accordion with one item that starts collapsed?

### ISSUE THREAD

**Issue by sherpadougs** [daviferreira/react-sanfona#494]
This feels like a really silly question, but I can't get it to happen. I've tried setting expanded= false in the AccordionItem as well as sending an empty array to Accordion, as well as a bunch of other things. I stuck a console.log in the node_modules for this telling me what expanded is, and it's always true, even though I've explicitly set it to false.

This is my code:

		<Accordion
			expanded={[]}
			onChange={this.toggleIsFilterMenuVisible}
		>
			<AccordionItem
				className="top-ten__filter"
				expanded={false}
				key={"filters"}
				title={"AccordionItem"}
			>
				<div className="top-ten__filter-container">
					{
						// Stuff in here...
					}
				</div>
			</AccordionItem>
		</Accordion>

I know the chances of this being my misunderstanding rather than an actual bug are pretty high - what am I doing wrong?

**Comment by sherpadougs** [comment]
After messing about in the code for a bit, I figured out that I needed to set `slug` in my props, not `key`. The documentation doesn't reflect this but it works fine this way, and the Accordion component checks the `slug` prop, defaulting to the index to create the key if it doesn't find it. I'd be happy to submit a PR if that would be helpful.

**Comment by daviferreira** [comment]
Yes, please submit a PR :)

**Comment by sherpadougs** [comment]
Well, it looks like the problem has been fixed since version 0.0.15, which my company is using. Forgot to check that part. oops :)
