### ISSUE TITLE
Peer dependencies broken

### ISSUE THREAD

**Issue by calebcassel** [daviferreira/react-sanfona#52]
I think this needs to be republished to NPM. The `package.json` I'm getting back after `npm install` has react and react-dom set to version `0.14.0`, while the source on Github has it at `^0.14.2`. This is preventing me from being able to try out your project since I have React 0.14.3, and the peer dependencies aren't being fulfilled.

**Comment by daviferreira** [comment]
Done, `0.0.8` is out. Thanks, forgot about it!

**Comment by calebcassel** [comment]
Thanks! Everything is looking great so far.
