### ISSUE TITLE
Update to react v15.0

### ISSUE THREAD

**Issue by kachkaev** [daviferreira/react-sanfona#61]
See https://facebook.github.io/react/index.html

After upgrading to react@15.0.1 npm starts complaining:
```
npm WARN react-sanfona@0.0.10 requires a peer of react@^0.14.3 but none was installed.
```

Patch example: https://github.com/STRML/react-grid-layout/commit/ef335bcc11652df0ff7cd649d9bc265acf339faf
(not submitting a PR since I don't know whether it is just about changing a version or there should be some modifications in the code too)

**Comment by psimyn** [comment]
I think if since there's no warnings it shouldn't need any changes -  `|| ^15.0.0` to peer deps and should be good to go
