### ISSUE TITLE
Improve import in JavaScript ES6

### ISSUE THREAD

**Issue by kachkaev** [daviferreira/react-sanfona#63]
When using ES6, it is required to write two lines of code to import the React components:
```js
import ReactSanfona from 'react-sanfona';
const { Accordion, AccordionItem } = ReactSanfona;
```
It would be nice if this could be done in a more standard way, like this:
```js
import { Accordion, AccordionItem } from 'react-sanfona';
```

E.g. like in [`react-grid-layout`](https://github.com/STRML/react-grid-layout).

**Comment by psimyn** [comment]
Are you using babel or plain ES6?

One line way seems to work for me:

```
import {Accordion, AccordionItem} from 'react-sanfona';
```

**Comment by kachkaev** [comment]
I'm trying to run this in Meteor 1.3, which must be using es6 + babel.

```js
import { Accordion, AccordionItem } from 'react-sanfona';
console.log('loaded', Accordion, AccordionItem); // loaded undefined undefined
```

**Comment by psimyn** [comment]
I think this is because `src/index.js` is using export.default - adding `export { Accordion, AccordionItem }` should work, I will confirm it doesn't break stuff

thanks for the examples

**Comment by daviferreira** [comment]
@psimyn Hey Simon, could you drop me an e-mail at hi@daviferreira.com?
