### ISSUE TITLE
onActiveItemsChange

### ISSUE THREAD

**Issue by kachkaev** [daviferreira/react-sanfona#64]
It would be really useful to add an event handler that would trigger when a set of active items has changed. I was going to use it to save the state of the accordion to my global state objects so that the clients that are looking at the same page could always be in sync.

Could you please add this feature? There should not be much to write.

**Comment by psimyn** [comment]
I am thinking onChange handler, just need to think of good place to put it

Would you want anything other than newState passed to it?

**Comment by psimyn** [comment]
@kachkaev see if that PR works for you

**Comment by kachkaev** [comment]
Hi @psimyn. Thanks for responding and for the PR!

I'm not sure I will be able to check the PR inside my project in the next couple of weeks — could anyone else have a look at it please? The code seems OK — I haven't spotted anything suspicious.

**Comment by psimyn** [comment]
Definitely nothing suspicious :) I'll confirm it can do what you were after then will probably merge
