### ISSUE TITLE
Event onClick on Each AccordionItem?

### ISSUE THREAD

**Issue by reyhansofian** [daviferreira/react-sanfona#77]
Is there a way to add an onClick event on each AccordionItem? I need to dispatch an action every time user click the AccordionItem. I've tried to add onClick event directly to the AccordionItem, but it doesn't work. This is what I've tried so far

```
<AccordionItem
  title={`Room Details for ${this.props.nights} nights`}
  titleClassName="panel-heading"
  onClick={() => this.changeActiveForm('room-breakdown')}
>
```

**Comment by psimyn** [comment]
Good find! it currently gets eaten by the Accordion (since it's used to trigger the open/close of that item).

There is the `onChange` handler that gets triggered when you change anything (clicking any item) that gets an array of activeItems.

If you wanted to set an onClick on an AccordionItem, would you want it to override the existing one, or be called before/after it?

**Comment by reyhansofian** [comment]
I've read the `onChange` handler, unfortunately it doesn't suit my needs. Regarding `onClick` handler, I prefer to override the existing one since I need more freedom to the `onClick` handler

**Comment by psimyn** [comment]
yeah, I think onChange needs a bit of thinking (was added for a pretty specific case).

Only problem with overriding the `onChange` is you would still need to call `setState` on the Accordion - it currently only uses activeItems props for initialisation (which is probably actually a bug).

If you were to override onChange, then the Accordion state would need to be completely handled outside of it 

I pushed a quick (break-y) trial of this to https://github.com/psimyn/react-sanfona/tree/onchange-science - want to have a try of that and see if it suits?

**Comment by reyhansofian** [comment]
sure! I'll give it a shot. Btw, your depencies is out of date. 

```
npm WARN deprecated autoprefixer-loader@3.1.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
```

**Comment by reyhansofian** [comment]
@psimyn it's perfect! I can use this for sure

**Comment by psimyn** [comment]
cool, I'll need to give that a little cleanup to allow for self-handled or externally handled, but should get something up today. Will at least push a branch for some more testing

Will also bump the deps :)

**Comment by reyhansofian** [comment]
cool, thanks a lot! 👍

**Comment by psimyn** [comment]
Got PR #78 if you'd like to have a try. Accordion exports `updateItems` function in case you want similar/same behaviour for the activeItems update.

I want to have a bit more of a think before merging this one, but this should get you started

@daviferreira any ideas/feedback?

**Comment by reyhansofian** [comment]
@psimyn great works! thanks a lot
