### ISSUE TITLE
Make heading configurable in AccodionTitleItem

### ISSUE THREAD

**Issue by fabarea** [daviferreira/react-sanfona#79]
Would be nice to have the ```<h3>``` configurable in https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItemTitle/index.jsx#L16. It does not necessary suit the rest of the markup semantic in the application.

Thanks for your nice module! :)

**Comment by psimyn** [comment]
I've found this as well, and have decorated the title with pseudo elements. I'll try updating so it can take a string or a Component, there may be a few gotchas if passing a component for title though (it would override onclick and a few other props) 

Do you have an example that you'd want to use so I can use it to test? 

Thanks!

**Comment by fabarea** [comment]
Nothing I could more precisely point out. It should appear more or less as a Bootstrap Accordion for my case... I work around by adjusting the style for ".react-sanfona-item h3". As well I had trouble with the [hardcoded inline CSS](https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItemTitle/index.jsx#L9), e.g. border: 0, I could figure something out by adjusting other CSS classes but it is not ideal. Being able to integrate a **custom accordion title component** would be very nice - which I was first expecting when discovering this module.

**Comment by fabarea** [comment]
Here would be some more precise use case for the Title Item:
![image](https://cloud.githubusercontent.com/assets/620730/15855405/9e9d63ce-2caf-11e6-8b99-2c79b71a7f72.png)

**Comment by psimyn** [comment]
Awesome, thanks. I'll try to have a pass at this tonight, will depend on some other PRs though. Custom button or something in the title (I am assuming that is 'delete'?) is an interesting idea.

In the meantime, if just for the arrows you could use some CSS

```
.react-sanfona-item-title {
  position: relative;
}

.react-sanfona-item-title:after {
  position: absolute;
  content: url(chevron.svg); /* can use icon font here if you'd rather */
  right: 1em;
}

.react-sanfona-item-expanded .react-sanfona-item-title:after {
  transform: rotate(180deg);
}
```

**Comment by fabarea** [comment]
Thanks. Yes, that's a delete action for now but it could / will be other actions coming for sure.

Ok for the arrows. I went with something exactly like that but didn't think of using ```content: url```, so 👍

**Comment by psimyn** [comment]
Just had a quick run at this, the change allows AccordionTitle `title` prop to be a string or a component. It keeps the default onClick so the Accordion still works, this means if you want other elements on there (e.g. the close/arrow icons above) you need to stop the event from propagating.

Here's an example of using it:

```
       <Accordion
          allowMultiple={true}
          activeItems={2}
        >
          {[1, 2, 3, 4, 5].map((item) => {
            const title = (
              <h2>
                <span>Item { item }</span>
                <span style={{float: 'right'}} onClick={(evt) => {
                  alert('click')
                  evt.stopPropagation()
                }}>x</span>
              </h2>
            )

            return (
              <AccordionItem title={title} key={item}>
                <div>
                  {`Item ${ item } content`}
                </div>
              </AccordionItem>
            );
          })}
        </Accordion>
```

I'll try to clean up the onClick stuff a bit with this as well

**Comment by hannupekka** [comment]
I'd love this feature too 👍

**Comment by vanoMekantsishvili** [comment]
@psimyn What you wrote it works perfeclty but when I put title component in another file then it won't and doesn't shows any error, any ideas :? :/
