### ISSUE TITLE
Issue with transitions on Safari 

### ISSUE THREAD

**Issue by p0o** [daviferreira/react-sanfona#80]
I faced some weird animations on Safari 8.0.8 with MacOS. Digging into the DOM did show me that there is a max-height value for accordion-item-body which is adding up to something close to 100px on my click and then less than a second changes back to none. Any ideas?

![accordion-bug](https://cloud.githubusercontent.com/assets/11336468/17058122/33434268-5051-11e6-8ee2-9dfbdebdccea.gif)

**Comment by psimyn** [comment]
thanks for reporting, and the GIF!

Seems like safari animates the switch to `max-height: none;` as if setting `max-height: 0` first; looks the same in 9 (testing in browserstack)

Made a demo here: http://codepen.io/psimyn/pen/zBWQjr

Hover to expand, then click (and hold) should cause flicker. The commented line of CSS in the pen is possibly an option (unset the animation when setting `max-height: none`

**Comment by p0o** [comment]
Yes, that's exactly what happened. Seems like Safari has a different interpretation of none value in `max-height`. 

By the way, looking at the code it seems max-height is only used to keep the integrity of animations. Why not just calculate the `height` as it seems to work well with Safari as well.

**Comment by psimyn** [comment]
I'll have a look at switching to height. Main advantage of using max-height is you can make it work without JS, but since nothing else does at the moment that doesn't seem worthwhile.

If you want to submit a PR for changing to height would be good, otherwise I'll have a look over the weekend

**Comment by p0o** [comment]
Yes, give me so some time and I will try to figure it out today or tomorrow.

**Comment by Alorse** [comment]
Some progress on this issue?
Thank you very much.

**Comment by maxnowack** [comment]
I've submitted a PR (#93) which should fix this issue

**Comment by ivchenkodima** [comment]
@p0o Have you fix this issue?

**Comment by SuttJ** [comment]
I'm still having this issue on Safari mobile.

**Comment by daviferreira** [comment]
https://github.com/daviferreira/react-sanfona/commit/aa3224eff630e9aa8f9a4adb4a4610c0e28330cf
