### ISSUE TITLE
Create new release based on #83

### ISSUE THREAD

**Issue by akiroz** [daviferreira/react-sanfona#84]
The current latest release doesn't work in a module-less environment (i.e. included by a `<script>` tag) due to ReactDOM missing from webpack externals.
Would be nice to have a new release based on #83 so I could update my dependencies.

Thanks!

**Comment by brukh** [comment]
hey @akiroz I pushed a updated release but need permission to publish to npm. Once I get access I will publish immediately. Thanks for being patient 😁

**Comment by brukh** [comment]
@akiroz should be good to go! Let me know if you run into any issues 👍🏽

**Comment by akiroz** [comment]
@brukh 
mind tagging the new release on github as well?

**Comment by brukh** [comment]
@akiroz will do! 😁
