### ISSUE TITLE
Cannot read property 'slug' of undefined

### ISSUE THREAD

**Issue by hydr4n7** [daviferreira/react-sanfona#85]
Hi.
Got a problem with displaying accordion, no matter what I do I always end up with an : `Uncaught TypeError: Cannot read property 'slug' of undefined` . If I replace accordion with my own component everything goes smoothly. If I click second time on the link to faqs I got : `Uncaught TypeError: Cannot read property 'getHostNode' of null     -     ReactReconciler.js:64`
Anyone ?

```
const faqsList = !isLoaded(faqs)
    ? 'Loading'
      : isEmpty(faqs)
    ? 'Faqs list is empty'
      : Object.keys(faqs).map(
          (key, id) => {
              <AccordionItem title={key} key={key} id={id} slug={key} >
                <div> {faqs[key]} </div>
              </AccordionItem>
          }
      )
return (
  <div>
    <h1>FAQS</h1>
      <Accordion
        allowMultiple={true}
      >
        {faqsList}
      </Accordion>
      <input type="text" ref="newFaq" />
      <button onClick={handleAdd}>
        Add
      </button>
  </div>
)
```

**Comment by psimyn** [comment]
your faqsList isn't returning any items. you need either a return statement, or change `{` to `(`

```
(key, id) => (
  <AccordionItem title={key} key={key} id={id} slug={key} >
    <div> {faqs[key]} </div>
  </AccordionItem>
)
```

or 

```
(key, id) => {
  return (<AccordionItem title={key} key={key} id={id} slug={key} >
    <div> {faqs[key]} </div>
  </AccordionItem>)
}
```

**Comment by hydr4n7** [comment]
I did that, and tons of other things. Nothing seems to be working. If I replace accordion with my own component its all alright.

```
    return (
      <div>
        <h1>FAQS</h1> 
            {!isLoaded(faqs)
              ? 'Loading'
                : isEmpty(faqs)
              ? 'Faqs list is empty'
                : Object.keys(faqs).map(
                  (key, id) => (
                    <FaqsItem title={key} key={key} id={key} question={key} answer={faqs[key]}/>           
              )
          )}
          <input type="text" ref="newFaq" />
          <button onClick={handleAdd}>
            Add
          </button>
      </div>
    )
```

FaqsItem.js component 
```

	return (    
			<div>
				{this.props.question}
				{this.props.answer}
			</div>
   
	);
```

**Comment by psimyn** [comment]
can you `console.log` the faqs in your above example? Otherwise if you can link to a runnable example I can take a look.

**Comment by brukh** [comment]
I'm going to close this for now but if your issue isn't resolved please provide us with some code @hydr4n7 👍

**Comment by eric-burel** [comment]
Hi, I have the same `Uncaught TypeError: Cannot read property 'slug' of undefined`.
I'll try to send code to repro.

**Comment by eric-burel** [comment]
Hi, 
This actually happens when you autogenerate the `AccordionItem` :+1: 

```javascript
<Accordion>
      <AccordionItem title="foo" slug="bar">
        hello
      </AccordionItem>
      {[1, 2, 3, 4, 5].map(function (item) {
        return (
          <AccordionItem title={'Item' + item} key={item} titleColor="blue">
            <div>
              {'Item ' +  item + ' content'}
              {item === 3 ? <p><img src="https://cloud.githubusercontent.com/assets/38787/8015584/2883817e-0bda-11e5-9662-b7daf40e8c27.gif" /></p> : null}
            </div>
          </AccordionItem>
        );
      })}
    </Accordion>
```

In the file `react-sanfona/src/Accordion/index.jsx` line 73, `item.props` is not defined.
I am not fluent in React, though I guess this is related to the fact that item can be either a `ReactElement` (with props) or a function (so with no `props`).

My React version : 15.3.2
My React-sanfona version : 0.0.15

**Comment by eric-burel** [comment]
Okay I got it, your `arrayify` function seems incorrect, it does work when all children are of the same type (either `Object` or `Array`), but it does not work on a mix of objects and array (like in my previous sample).
For example : 
```javascript
<Accordion>
      {[1, 2, 3, 4, 5].map(function (item) {
        return (
          <AccordionItem title={'Item' + item} key={item} titleColor="blue">
            <div>
              {'Item ' +  item + ' content'}
              {item === 3 ? <p><img src="https://cloud.githubusercontent.com/assets/38787/8015584/2883817e-0bda-11e5-9662-b7daf40e8c27.gif" /></p> : null}
            </div>
          </AccordionItem>
        );
      })}
    </Accordion>
```
and 
```javascript
<Accordion>
      <AccordionItem title="foo" slug="bar">
        hello
      </AccordionItem>
      <AccordionItem title="bar" slug="foo">
        world
      </AccordionItem>
    </Accordion>
```
both work, but not when we mix arrays and objects.

**Comment by psimyn** [comment]
thanks @eric-burel ! Will look into a fix

**Comment by pretentiousgit** [comment]
This also breaks if you have an undefined array that populates on a repeated load of content into that array.
