### ISSUE TITLE
onExpand doesn't handle specific item

### ISSUE THREAD

**Issue by mic3ael** [daviferreira/react-sanfona#90]
onExpand doesn't return a key of accordion item, I want to know the slug key of expended accordion item.

I did it by my self just added to `accordionItem/index.js`

```
handleExpand() {
    const {onExpand, # slug} = this.props;

    this.startTransition();
    this.timeout = setTimeout(() => {
      this.setState({maxHeight: 'none', overflow: 'visible'});

      if (onExpand) {
        onExpand(# slug);
      }

    }, this.state.duration);
  }
```

Now onExpand callback is running with slug value.

Could you add that to repo? 
Thanks.

**Comment by brukh** [comment]
Thanks for the contribution @mic3ael! I went ahead and implemented it. Should be available on the next release 👍
