### ISSUE TITLE
Getting Uncaught Invariant Violation in console warning 

### ISSUE THREAD

**Issue by sreevarsh** [daviferreira/react-sanfona#94]
Hi,
I tried to use react-sanfona in my project but, getting the bellow warning in browser console

> You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure
> 
I followed the example that is in demo folder.
can you please let me know how to resolve this?

**Comment by psimyn** [comment]
this is due to using uuid for rendering. I think we can probably change that to be conditional, then you specify your own ID for each accordionitem.

I'll try having a look this evening

**Comment by brukh** [comment]
If you can please post some sample code that would be helpful! @sreevarsh

**Comment by sreevarsh** [comment]
Hi,
This is how I used the component
`<Accordion id="calReportAccordion" allowMultiple={true} activeItems={[0, 1]}>
{this.state.data.map((dat, i) => {
return (
<AccordionItem id="accordionid" onClose={() => this.hideType()} onExpand={() => this.showType()} title={title} slug={i} key={ch._id} allowMultiple={true} expanded={true}>
<Table> 
.....  
</Table>                                                                    
</AccordionItem>)
}}
</Accordion>`

**Comment by sreevarsh** [comment]
@brukh is there any possible solution for this issue? - Thanks

**Comment by psimyn** [comment]
Generating the UUID in `componentDidMount` will get rid of the error, but doesn't quite fix the issue of needless first update. Made [a PR](https://github.com/daviferreira/react-sanfona/pull/99) with the simplest solution from this side - people set uuid themselves so we don't worry ourselves checking for uniqueness

https://github.com/facebook/react/issues/4000 is potentially worth keeping an eye on for a better solution

**Comment by psimyn** [comment]
@sreevarsh since 0.1 you can now pass uuid to each AccordionItem as a prop. You'll need to make sure the IDs you use are unique for all AccordionItems, but should be a simple way to fix server render for now

**Comment by sreevarsh** [comment]
Thank you @psimyn , It worked
