### ISSUE TITLE
'expanded' props is always false

### ISSUE THREAD

**Issue by alfredoreduarte** [daviferreira/react-sanfona#95]
Is anyone having a problem with the `expanded` prop? It seems like it's always being overwritten to `false`.

**Comment by brukh** [comment]
Can you please provide a code sample? @alfredoreduarte

**Comment by gbenson-wikia** [comment]
I encountered this today as well.  Here's a sample:

```
<Accordion className="example" allowMultiple>
    <AccordionItem title={'example_1'} expanded>
        Hello, bug 1.
    </AccordionItem>
    <AccordionItem title={'example_2'} expanded>
        Hello, bug 2.
    </AccordionItem>
</Accordion>
```

**Comment by psimyn** [comment]
it gets set based on the activeItems prop from the Accordion [here](https://github.com/daviferreira/react-sanfona/blob/master/src/Accordion/index.jsx#L74). That overrides the expanded prop

I think it's intended more for internal-use by `Accordion` - allowing it to be set could get a bit confusing. @alfredoreduarte did you have a use-case for wanting to set it? Otherwise might just remove it from docs

**Comment by gbenson-wikia** [comment]
It might just be syntactic sugar, but if I've got the ability to have multiple items open simultaneously, it'd be nice to be able to specify which set of them are initially expanded in a more declarative way (as in the sample).  Though, I can see how that'd cause confusion and complicated edge cases.   ¯\_(ツ)_/¯

**Comment by psimyn** [comment]
I think ORing it with activeItems could still make sense. But it might raise further questions. example:

```
<Accordion className="example" allowMultiple={false} activeItems=[0]>
    <AccordionItem title={'example_1'}>
        Hello, bug 1.
    </AccordionItem>
    <AccordionItem title={'example_2'} expanded>
        Hello, bug 2.
    </AccordionItem>
</Accordion>
```

**Comment by zaros** [comment]
Same here. I'm trying to let my app remember which accordions a user had open since their last session.

**Comment by cwhittl** [comment]
Having the same issue here, I just want to set an accordionitem expanded and the prop is completely ignored.

**Comment by s-mikulich** [comment]
Hi, I have the same issue.

**Comment by timsmith339** [comment]
The whole reason I went with this package was because I saw the expanded property.  Why would it not work?

**Comment by daviferreira** [comment]
Hey guys, I've just published `v1.0.0-rc2` that should address this issue. Could you please test it and see if everything is ok? PR is here if you feel like reviewing it :) https://github.com/daviferreira/react-sanfona/pull/127

Please notice that I've removed the `activeItems` prop altogether, so active state should now be handled only via `expanded` prop.

**Comment by wawhal** [comment]
@psimyn It goes back to collapsed state even when you use the activeElements tag.
Refer to #126 for my problem in detail. I tried to achieve the same thing using this following code:
```
<Accordion activeItems={expandedIndex}>
{SomeAccordionItem}
{SomeAccordionItem}
</Accordion>
```
I am using redux. The variable `expandedIndex` comes from redux state. So when a state change happens after I click one of the elements from the array inside AccordionItem, and the component re-renders, all go back to collapsed. Say if `expandedIndex` is 0 after a re-render, the first accordion item should be expanded right? It isn't. Tell me if I wasn't clear enough.

**Comment by daviferreira** [comment]
@wawhal can you test with `1.0.0-rc3`? You will need to change your code to set the `expanded` prop on the items instead since I'm removing the `activeItems` prop. You can check this example: https://github.com/daviferreira/react-sanfona/blob/77d5cd01c82eb5c04984d6aacdcbe5234bdf8fc0/demo/index.js#L44

**Comment by wawhal** [comment]
@daviferreira It works. Thanks for the help.

**Comment by timsmith339** [comment]
@daviferreira and @wawhal Thank you for fixing that, and wonderful package.

**Comment by mikeybags** [comment]
I feel like this might be related, but feel free to let me know if I should bring this up elsewhere. I am using this in conjunction with pagination (showing 10 accordionItems per page). When changing pages, if the first item of a page was open, the first item on the new page remains open. I tried setting a variable to false on page change (and use that variable for the expanded prop), but the accordion remains open upon page change. Any suggestions?
